
trigger:
- master
- coverage

jobs:
- job: Conjure
  timeoutInMinutes: 0
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
        runTests: true
        coverage: false
      Mac:
        imageName: 'macos-latest'
        runTests: true
        coverage: false
      Windows:
        imageName: 'vs2017-win2016'
        runTests: false
        coverage: false
      CodeCoverage:
        imageName: 'ubuntu-latest'
        runTests: true
        coverage: true
  pool:
    vmImage: $(imageName)
  steps:
  - bash: BIN_DIR=${HOME}/.local/bin PATH=${HOME}/.local/bin:${PATH} COVERAGE=$(coverage) BUILD_TESTS=true make
    displayName: "Build Conjure"
  - bash: if $(runTests) ; then BIN_DIR=${HOME}/.local/bin PATH=${HOME}/.local/bin:${PATH} etc/build/install-minion.sh ; fi
    displayName: "Install Minion"
  - bash: if $(runTests) ; then BIN_DIR=${HOME}/.local/bin PATH=${HOME}/.local/bin:${PATH} etc/build/install-glucose.sh ; fi
    displayName: "Install Glucose"
  - bash: if $(runTests) ; then BIN_DIR=${HOME}/.local/bin PATH=${HOME}/.local/bin:${PATH} COVERAGE=$(coverage) LIMIT_TIME=0 make test ; fi
    displayName: "Test"
  - bash: if $(coverage) ; then find . -name '*.tix' ; fi
    displayName: "List tix files"

